version: '2'
services:
  namesrv:
    image: apache/rocketmq:5.1.3
    container_name: rmqnamesrv
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.1.3
    container_name: rmqbroker
    ports:    
      - 10911:10911
      - 8081:8081
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/home/rocketmq/rocketmq-5.1.3/conf/broker.conf
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf --enable-proxy
    depends_on:
      - namesrv
  dashboard:
    image: apacherocketmq/rocketmq-dashboard
    container_name: rocketmq_dashboard
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=falses